[package]
name = "gol"
version = "0.1.0"
authors = ["Jonathan Tremesaygues <jonathan.tremesaygues@slaanesh.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
piston = "0.50"
piston_window = "0.98"
